### ISSUE TITLE
Cannot find the include-fragment

### ISSUE THREAD

**Issue by DCNick3** [Sec-ant/github-feed-back#2] opened 2023-09-08 05:43 UTC
The script doesn't seem to work for me. The `'[data-target="feed-container.content"] > include-fragment'` selector doesn't find anything, because there's no `include-fragment` in the feed-container. Instead it contains only a `turbo-frame`, which has no `src` property..

**Comment by Sec-ant** [comment] 2023-09-08 05:45
Hey, could you tell your device/OS/browser and Tampermonkey/Violentmonkey info?

**Comment by DCNick3** [comment] 2023-09-08 05:49
I am on a Arch Linux, using Firefox 116.0.2, using latest Tampermonkey

**Comment by Sec-ant** [comment] 2023-09-08 06:14
`<inlude-fragment>` is present before the content in it is actually loaded:

![image](https://github.com/Sec-ant/github-feed-back/assets/10386119/c9559087-82e9-4538-8cc3-46eeb4bfce1f)

So this script is required to run as early as possible, normally the `@run-at: document-start` meta property should be enough: https://github.com/Sec-ant/github-feed-back/blob/e3e6ecc09550a761871d2d2fbc09c7ea2b54fc18/vite.config.ts#L21

I cannot reproduce this problem on my Firefox 116.0.2. Is the `run-at` property possibly be overridden by some of your settings in Tampermonkey?

**Comment by DCNick3** [comment] 2023-09-08 06:21
![image](https://github.com/Sec-ant/github-feed-back/assets/10363282/0714db6e-544e-413c-a620-136f985a19be)

Hm, so my initial assumption was wrong.. It _does_ find the element and seems to successfully replace the `src`, but github still seems to load the original feed. Maybe it's some kind of timing issue? github starting the request to load the new feed before the script replaces the `src`..

**Comment by DCNick3** [comment] 2023-09-08 06:30
Ok, so, curiously, `includeFragment.src` does _not_ correspond to the `src` attribute of the tag (not sure if this is a firefox thing or smth else). Changing it to `includeFragment.setAttribute("src", "/dashboard-feed");` make the script work!

**Comment by Sec-ant** [comment] 2023-09-08 06:42
Glad to hear the good news. Thanks for the fix.

Seems like a web component with buggy implementation. I'm now closing this.

**Closed** 2023-09-08 06:42 UTC
